/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LabGuide7;

import Memory.Alzheimer;
import Memory.Amnesia;

/**
 *
 * @author lenovo
 */
public class MemoryApp extends javax.swing.JFrame {
    
    InfoClass infoClass = new InfoClass();

    
    public MemoryApp() {
        initComponents();
        
        pnAmn.setVisible(false);
        pnAlzh.setVisible(false);
        jPanel1.setVisible(true);
        
    }
    
    public void ClearAll(){
        tfDefictID.setText("");
        tfAge.setText("");
        tfPatientID.setText("");
        tfgender.setText("");
        tfPatientns.setText("");
        cbMemoryLoss.setSelectedIndex(-1);
        buttonGroup1.clearSelection();
        pnAlzh.setVisible(false);
        pnAmn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnDisp = new javax.swing.JPanel();
        btDisp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisp = new javax.swing.JTextArea();
        btTotalDef = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfTotalDef = new javax.swing.JTextArea();
        pnMemory = new javax.swing.JPanel();
        lbDefictID = new javax.swing.JLabel();
        lbMemoryLoss = new javax.swing.JLabel();
        tfDefictID = new javax.swing.JTextField();
        cbMemoryLoss = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPname = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        tfPatientns = new javax.swing.JTextField();
        tfPatientID = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        lbGender = new javax.swing.JLabel();
        tfgender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdAmn = new javax.swing.JRadioButton();
        rdAlz = new javax.swing.JRadioButton();
        btAdd = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnAmn = new javax.swing.JPanel();
        lbType = new javax.swing.JLabel();
        lbCause = new javax.swing.JLabel();
        lbBrain = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        cbCause = new javax.swing.JComboBox<>();
        cbBrain = new javax.swing.JComboBox<>();
        pnAlzh = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbEff = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taSearch = new javax.swing.JTextArea();
        btSearchDef = new javax.swing.JButton();
        cbSearch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnDisp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Display And Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        btDisp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btDisp.setText("Display Deficit");
        btDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDispActionPerformed(evt);
            }
        });

        taDisp.setEditable(false);
        taDisp.setColumns(20);
        taDisp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        taDisp.setForeground(new java.awt.Color(51, 51, 51));
        taDisp.setRows(5);
        jScrollPane1.setViewportView(taDisp);

        btTotalDef.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btTotalDef.setText("Total Deficit");
        btTotalDef.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btTotalDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalDefActionPerformed(evt);
            }
        });

        tfTotalDef.setColumns(20);
        tfTotalDef.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tfTotalDef.setRows(5);
        jScrollPane2.setViewportView(tfTotalDef);

        javax.swing.GroupLayout pnDispLayout = new javax.swing.GroupLayout(pnDisp);
        pnDisp.setLayout(pnDispLayout);
        pnDispLayout.setHorizontalGroup(
            pnDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDispLayout.createSequentialGroup()
                .addComponent(btDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnDispLayout.createSequentialGroup()
                .addGroup(pnDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnDispLayout.createSequentialGroup()
                        .addComponent(btTotalDef, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnDispLayout.setVerticalGroup(
            pnDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDispLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTotalDef, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnMemory.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Memory Defict", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lbDefictID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDefictID.setText("Defict id");

        lbMemoryLoss.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbMemoryLoss.setText("Memory Loss");

        tfDefictID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDefictIDActionPerformed(evt);
            }
        });

        cbMemoryLoss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Implicit", "Explicit", "Item 3", "Item 4" }));
        cbMemoryLoss.setSelectedIndex(-1);
        cbMemoryLoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemoryLossActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Clinical Cases");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Patient ID:");

        lbPname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbPname.setText("Patient name, surname:");

        lbAge.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbAge.setText("Age:");

        tfPatientns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPatientnsActionPerformed(evt);
            }
        });

        tfPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPatientIDActionPerformed(evt);
            }
        });

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbGender.setText("Gender");

        tfgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgenderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Deficit Type:");

        buttonGroup1.add(rdAmn);
        rdAmn.setText("Amnesia");
        rdAmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAmnActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdAlz);
        rdAlz.setText("Alzheimer");
        rdAlz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlzActionPerformed(evt);
            }
        });

        btAdd.setText("Add Deficit");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        pnAmn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Amnesia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        pnAmn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbType.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbType.setText("Type:");

        lbCause.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbCause.setText("Cause:");

        lbBrain.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbBrain.setText("Brain Location:");

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refregrade", "Item 2", "Item 3", "Item 4" }));

        cbCause.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brain Infection", "Item 2", "Item 3", "Item 4" }));
        cbCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCauseActionPerformed(evt);
            }
        });

        cbBrain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hippocampus", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnAmnLayout = new javax.swing.GroupLayout(pnAmn);
        pnAmn.setLayout(pnAmnLayout);
        pnAmnLayout.setHorizontalGroup(
            pnAmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAmnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnAmnLayout.createSequentialGroup()
                        .addComponent(lbBrain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBrain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAmnLayout.createSequentialGroup()
                        .addComponent(lbCause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCause, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAmnLayout.createSequentialGroup()
                        .addComponent(lbType)
                        .addGap(94, 94, 94)
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        pnAmnLayout.setVerticalGroup(
            pnAmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAmnLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnAmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnAmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCause)
                    .addComponent(cbCause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnAmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBrain)
                    .addComponent(cbBrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnAlzh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Alzheimer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Affected Area");

        cbEff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Istanbul", "Bolu", "Van" }));

        javax.swing.GroupLayout pnAlzhLayout = new javax.swing.GroupLayout(pnAlzh);
        pnAlzh.setLayout(pnAlzhLayout);
        pnAlzhLayout.setHorizontalGroup(
            pnAlzhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlzhLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(cbEff, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnAlzhLayout.setVerticalGroup(
            pnAlzhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlzhLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnAlzhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(pnAmn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnAlzh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAmn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(pnAlzh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(pnAmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnAlzh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnMemoryLayout = new javax.swing.GroupLayout(pnMemory);
        pnMemory.setLayout(pnMemoryLayout);
        pnMemoryLayout.setHorizontalGroup(
            pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMemoryLayout.createSequentialGroup()
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMemoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnMemoryLayout.createSequentialGroup()
                                .addComponent(lbDefictID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfDefictID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnMemoryLayout.createSequentialGroup()
                                .addComponent(lbMemoryLoss)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMemoryLoss, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnMemoryLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(pnMemoryLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMemoryLayout.createSequentialGroup()
                                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPname)
                                    .addComponent(jLabel2)
                                    .addComponent(lbAge)
                                    .addComponent(lbGender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAge, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(tfPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(tfPatientns)
                                    .addComponent(tfgender)))
                            .addGroup(pnMemoryLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(13, 13, 13)
                                .addComponent(rdAmn)
                                .addGap(18, 18, 18)
                                .addComponent(rdAlz))
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnMemoryLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnMemoryLayout.setVerticalGroup(
            pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMemoryLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDefictID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDefictID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMemoryLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMemoryLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPname)
                    .addComponent(tfPatientns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAge)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGender)
                    .addComponent(tfgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdAmn)
                    .addComponent(rdAlz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdd))
        );

        taSearch.setColumns(20);
        taSearch.setRows(5);
        jScrollPane3.setViewportView(taSearch);

        btSearchDef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSearchDef.setText("Search by Deficit ID");
        btSearchDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchDefActionPerformed(evt);
            }
        });

        cbSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSearch.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btSearchDef, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addComponent(pnDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSearchDef, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        setSize(new java.awt.Dimension(998, 814));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDefictIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDefictIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDefictIDActionPerformed

    private void cbMemoryLossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemoryLossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMemoryLossActionPerformed

    private void tfPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPatientIDActionPerformed

    private void tfPatientnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPatientnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPatientnsActionPerformed

    private void tfgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgenderActionPerformed

    private void rdAlzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlzActionPerformed
        if (rdAlz.isSelected() == true) {
            pnAmn.setVisible(false);
            pnAlzh.setVisible(true);
        }
    }//GEN-LAST:event_rdAlzActionPerformed

    private void rdAmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAmnActionPerformed
            if (rdAmn.isSelected() == true) {
            pnAmn.setVisible(true);
            pnAlzh.setVisible(false);
        }
    }//GEN-LAST:event_rdAmnActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        String defict_id = tfDefictID.getText();
        String memoryLoss = cbMemoryLoss.getSelectedItem().toString();
        String[] NS = new String[2];
        String name, surname;
        
        
        NS = tfPatientns.getText().split(",");
        name = NS[0];
        surname = NS[1];
        
        
        if((rdAmn.isSelected() == true)){
            Amnesia amnesia = new Amnesia(cbType.getSelectedItem().toString(),cbCause.getSelectedItem().toString(),cbBrain.getSelectedItem().toString(),defict_id,memoryLoss,tfPatientID.getText(),name,surname,Integer.parseInt(tfAge.getText()), tfgender.getText());
            infoClass.addMemory(amnesia);
            taDisp.append("Amnesia is Added!\n");
        }
        else if(rdAlz.isSelected() == true){
            Alzheimer alzheimer = new Alzheimer(cbEff.getSelectedItem().toString(),defict_id,memoryLoss,tfPatientID.getText(),name,surname,Integer.parseInt(tfAge.getText()), tfgender.getText());
            infoClass.addMemory(alzheimer);
            taDisp.append("Alzheimer is Added!\n");

        }
        
        btTotalDefActionPerformed(evt);
        
        cbSearch.addItem(defict_id);
        
        ClearAll();
    }//GEN-LAST:event_btAddActionPerformed

    private void btDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDispActionPerformed
        if (rdAlz.isSelected() == true) {
            pnAmn.setVisible(false);
            pnAlzh.setVisible(true);
            taDisp.setText(infoClass.getAlzheimer());
        }
        
        else if (rdAmn.isSelected() == true) {
            pnAmn.setVisible(true);
            pnAlzh.setVisible(false);
            taDisp.setText(infoClass.getAmnesia());
        }
        
        else{
            taDisp.setText(infoClass.getAllMemory());
        }
    }//GEN-LAST:event_btDispActionPerformed

    private void cbCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCauseActionPerformed

    private void btTotalDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalDefActionPerformed
        tfTotalDef.setText(infoClass.showTotalMemory());
    }//GEN-LAST:event_btTotalDefActionPerformed

    private void btSearchDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchDefActionPerformed
       taSearch.setText(infoClass.searchMemory(cbSearch.getSelectedItem().toString()).toString());
    }//GEN-LAST:event_btSearchDefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryApp().setVisible(true);
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDisp;
    private javax.swing.JButton btSearchDef;
    private javax.swing.JButton btTotalDef;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBrain;
    private javax.swing.JComboBox<String> cbCause;
    private javax.swing.JComboBox<String> cbEff;
    private javax.swing.JComboBox<String> cbMemoryLoss;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbBrain;
    private javax.swing.JLabel lbCause;
    private javax.swing.JLabel lbDefictID;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbMemoryLoss;
    private javax.swing.JLabel lbPname;
    private javax.swing.JLabel lbType;
    private javax.swing.JPanel pnAlzh;
    private javax.swing.JPanel pnAmn;
    private javax.swing.JPanel pnDisp;
    private javax.swing.JPanel pnMemory;
    private javax.swing.JRadioButton rdAlz;
    private javax.swing.JRadioButton rdAmn;
    private javax.swing.JTextArea taDisp;
    private javax.swing.JTextArea taSearch;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfDefictID;
    private javax.swing.JTextField tfPatientID;
    private javax.swing.JTextField tfPatientns;
    private javax.swing.JTextArea tfTotalDef;
    private javax.swing.JTextField tfgender;
    // End of variables declaration//GEN-END:variables
}
